export const ROBOT_CONFIG = {
    DEFAULT_PULSE_DURATION: 1000,
    DEFAULT_THROTTLE: 140,
    DEFAULT_COLOR: "#00d2ff",
    RECONNECT_INTERVAL: 3000,
    MOCK_UPDATE_INTERVAL: 100,

    // Physical Pin/Actuator Mapping
    PINS: {
        FRONT_LEFT: 25,
        FRONT_RIGHT: 4,
        REAR_LEFT: 14,
        REAR_RIGHT: 19,
        FL_REVERSE: 26,
        FR_REVERSE: 17,
        RL_REVERSE: 27,
        RR_REVERSE: 21,
    }
};

export const ACTUATOR_MAP: Record<string, number[]> = {
    "Arriba": [ROBOT_CONFIG.PINS.FRONT_LEFT, ROBOT_CONFIG.PINS.FRONT_RIGHT, ROBOT_CONFIG.PINS.REAR_LEFT, ROBOT_CONFIG.PINS.REAR_RIGHT],
    "Abajo": [ROBOT_CONFIG.PINS.FL_REVERSE, ROBOT_CONFIG.PINS.FR_REVERSE, ROBOT_CONFIG.PINS.RL_REVERSE, ROBOT_CONFIG.PINS.RR_REVERSE],
    "Izquierda": [ROBOT_CONFIG.PINS.FRONT_RIGHT, ROBOT_CONFIG.PINS.REAR_RIGHT, ROBOT_CONFIG.PINS.FL_REVERSE, ROBOT_CONFIG.PINS.RL_REVERSE],
    "Derecha": [ROBOT_CONFIG.PINS.FRONT_LEFT, ROBOT_CONFIG.PINS.REAR_LEFT, ROBOT_CONFIG.PINS.FR_REVERSE, ROBOT_CONFIG.PINS.RR_REVERSE],
};
